cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('success', views.success, name='order-success'),]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('users/', include('users.urls', namespace='users')),
    # path('users/', include('users.urls')),
    # path('users/', include('django.contrib.auth.urls')),

    path('about', views.about_brand, name='about-brand'),
    path('contacts', views.contacts, name='contacts'),
    path('', views.homepage, name='homepage'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration', views.registration, name='registration'),
    path('profile', views.profile, name='profile'),
    # path('', include('django.contrib.auth.urls'))
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'class',
        'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'class-here',
        'placeholder': 'Введите пароль'}))

    class Meta:  # класс отвечает, с какой моделью, полями работать, показываем, что нужно связать с моделью пользователей
        model = User
        fields = ('username',
                  'password')  # можно использовать список, но если кортеж и одно поле, то обязательно запятая после первого элемента должна быть


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'class',
        'placeholder': 'Введите имя '}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'class',
        'placeholder': 'Введите фамилию'}))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'class',
        'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'class',
        'placeholder': 'Введите e-mail '}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'class-here',
        'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'class-here',
        'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect
from users.forms import UserLoginForm, UserRegistrationForm
from django.contrib import auth
from django.urls import reverse


# Create your views here.

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        # username = form.cleaned_data.get('username')
        # password = form.cleaned_data.get('password')
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # username = request.POST['username']
            # password = request.POST['password']
            user = auth.authenticate(username=username,  # обязательно писать через равно, иначе ошибка!!
                                     password=password)  # аутентификация, есть ли с атким именем и паролем пользвоатель
            if user:
                auth.login(request, user)  # если польхователь есть, то он авторизуется
                return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserLoginForm()
        context = {'form': form}
        return render(request, 'users/login.html', context)


# def login(request):
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = auth.authenticate(username=username, password=password)
#         if user is not None and user.is_active:
#             auth.login(request, user)
#             context = {'user': user}
#             return HttpResponseRedirect(reverse('homepage'))
#         else:
#             context = {'user': None}
#             return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))  # когда зарегался, отправляем на страницу входа
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    # form = UserLoginForm()
    # context = {'form': form}
    return render(request, 'users/profile.html')

users/templates/users/base.html
{% extends 'main.html' %}
{% load static %}

{% block css_additional %}
    <link rel="stylesheet" href="{% static 'shop/css/shop_main_page.css' %}">
{% endblock %}

{% block title %} Магазин {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
{#        <a href="{% url 'logout' %}">logout</a>#}
    {% else %}
        <a href="{% url 'login' %}">login</a>
    {% endif %}
{% endblock %}

users/templates/users/login.html
{% extends 'main.html' %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'users/css/registration.css' %}">
    <link rel="stylesheet" href="{% static 'shop/css/add-product.css' %}">
{% endblock %}
{% block title %}Войти{% endblock %}
{% block content %}
    <div class="container ">
        <h1 class="title"> Войти</h1>
{#        <p style="margin-top: 300px">Войти</p>#}
        <form method="post" enctype="multipart/form-data" class="add-product" action="{% url 'users:login' %}">
            {% csrf_token %}
            <div class="reg-form">
                <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
                <label for="{{ form.password.id_for_label }}">Пароль</label>
                {{ form.password }}

                <button type="submit" class="btn-text">Войти</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'main.html' %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'users/css/registration.css' %}">
{% endblock %}
{% block title %}Личный кабинет{% endblock %}
{% block content %}
    <div class="container ">
        <h1 class="title"> Личный кабинет</h1>
        {#        <p style="margin-top: 300px">Войти</p>#}
{#        <h1 style="margin-top: 300px">Добро пожаловать!</h1>#}

    </div>

{% endblock %}

users/templates/users/registration.html
{% extends 'main.html' %}
{% load static %}
{% block css_additional %}
    <link rel="stylesheet" href="{% static 'users/css/registration.css' %}">
    <link rel="stylesheet" href="{% static 'shop/css/add-product.css' %}">
{% endblock %}
{% block title %}Регистрация{% endblock %}
{% block content %}
    <div class="container ">
        <h1 class="title"> Регистрация</h1>

        <div class="row">
        <form method="post" enctype="multipart/form-data" class="add-product" action="{% url 'users:registration' %}">
            {% csrf_token %}
            <div class="reg-form ">
                <label for="{{ form.first_name.id_for_label }}">Имя </label>
                {{ form.first_name }}
                <label for="{{ form.last_name.id_for_label }}">Фамилия </label>
                {{ form.last_name }}
                <label for="{{ form.username.id_for_label }}">Имя пользователя </label>
                {{ form.username }}
                <label for="{{ form.email.id_for_label }}">Email </label>
                {{ form.email }}
                <label for="{{ form.password1.id_for_label }}">Пароль</label>
                {{ form.password1 }}
                {{ form.errors}}
                <label for="{{ form.password2.id_for_label }}">Подтверждение пароля</label>
                {{ form.password2 }}

                <button type="submit" class="btn-text">Сохранить</button>
            </div>
        </form>


        </div>
    </div>
{% endblock %}